services:
  web:  # Django Web Service
    build: ./safestep/  # Folder with Dockerfile of Django
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./safestep:/Dev_tool-Project  # Mount Django code into the container
    ports:
      - "8000:8000"  # Open port for Django access
